services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_api
    restart: always
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PRODUCTION_MODE=true
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - social_network
    logging:
      driver: journald
      options:
        tag: "social_api"

  celery_worker:
    build: .
    container_name: social_worker
    command: celery -A app.celery_app worker --loglevel=info
    restart: always
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PRODUCTION_MODE=true
    depends_on:
      - redis
      - rabbitmq
    networks:
      - social_network
    logging:
      driver: journald
      options:
        tag: "social_worker"

  celery_beat:
    build: .
    container_name: social_beat
    command: celery -A app.celery_app beat --loglevel=info
    restart: always
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PRODUCTION_MODE=true
    depends_on:
      - redis
      - rabbitmq
    networks:
      - social_network
    logging:
      driver: journald
      options:
        tag: "social_beat"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - social_network
    logging:
      driver: journald
      options:
        tag: "redis"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - social_network
    logging:
      driver: journald
      options:
        tag: "rabbitmq"

volumes:
  redis_data:
  rabbitmq_data:

networks:
  social_network:
    driver: bridge
