[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session
filterwarnings =
	ignore:Call to '__init__' function with deprecated usage of input argument/s 'retry_on_timeout'.*:DeprecationWarning
	ignore:Call to '__init__' function with deprecated usage of input argument/s 'lib_name'.*:DeprecationWarning
	ignore:Call to '__init__' function with deprecated usage of input argument/s 'lib_version'.*:DeprecationWarning
	ignore:The garbage collector is trying to clean up non-checked-in connection.*:sqlalchemy.exc.SAWarning
