"""changed column name

Revision ID: 172f2a247dd1
Revises: 5bc72d322f9f
Create Date: 2025-10-19 18:25:29.222816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172f2a247dd1'
down_revision: Union[str, Sequence[str], None] = '5bc72d322f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('dis_likes', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('posts', 'disLikes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('disLikes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('posts', 'dis_likes')
    # ### end Alembic commands ###
