"""added hashtags column in posts table

Revision ID: 4dd4735f931c
Revises: ea2df79e66e2
Create Date: 2025-10-25 12:38:25.518376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd4735f931c'
down_revision: Union[str, Sequence[str], None] = 'ea2df79e66e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('hashtags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'hashtags')
    # ### end Alembic commands ###
