"""setting server defualts

Revision ID: 65a3372aeccd
Revises: ca01409f3fd7
Create Date: 2025-10-31 17:43:06.993183

"""
from typing import Sequence, Union
from sqlalchemy import text
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '65a3372aeccd'
down_revision: Union[str, Sequence[str], None] = 'ca01409f3fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix integer defaults
    op.alter_column(
        'users', 'followers_cnt',
        existing_type=sa.Integer(),
        server_default=text("0"),
        default=0,
        nullable=False
    )
    op.alter_column(
        'users', 'following_cnt',
        existing_type=sa.Integer(),
        server_default=text("0"),
        default=0,
        nullable=False
    )
    op.alter_column(
        'posts', 'likes',
        existing_type=sa.Integer(),
        server_default=text("0"),
        default=0,
        nullable=False
    )
    op.alter_column(
        'posts', 'dis_likes',
        existing_type=sa.Integer(),
        server_default=text("0"),
        default=0,
        nullable=False
    )
    op.alter_column(
        'posts', 'views',
        existing_type=sa.Integer(),
        server_default=text("0"),
        default=0,
        nullable=False
    )
    op.alter_column(
        'posts', 'comments_cnt',
        existing_type=sa.Integer(),
        server_default=text("0"),
        default=0,
        nullable=False
    )
    op.alter_column(
        'comments', 'likes',
        existing_type=sa.Integer(),
        server_default=text("0"),
        default=0,
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'followers_cnt', server_default=None, nullable=False)
    op.alter_column('users', 'following_cnt', server_default=None, nullable=False)
    # ### end Alembic commands ###
