"""autoincrement id col

Revision ID: 6b6f456de93c
Revises: d17fef7976fa
Create Date: 2025-10-23 19:29:48.124936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6f456de93c'
down_revision: Union[str, Sequence[str], None] = 'd17fef7976fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'comments',  # Replace with your table name
        'id',
        existing_type=sa.Integer(),
        autoincrement=True,
        existing_nullable=False, # Assuming primary key is non-nullable
        existing_autoincrement=None # Or False if it was explicitly set to False before
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'comments',  # Replace with your table name
        'id',
        existing_type=sa.Integer(),
        autoincrement=False, # Or None to revert to dialect's default
        existing_nullable=False, # Assuming primary key is non-nullable
        existing_autoincrement=True
    )

    # ### end Alembic commands ###
