"""follow table created

Revision ID: 6fcfbeba9f2c
Revises: ca2d874b6ea6
Create Date: 2025-10-22 14:16:45.893275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcfbeba9f2c'
down_revision: Union[str, Sequence[str], None] = 'ca2d874b6ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('connect_follower_id_fkey'), 'connect', type_='foreignkey')
    op.drop_constraint(op.f('connect_followed_id_fkey'), 'connect', type_='foreignkey')
    op.create_foreign_key(None, 'connect', 'users', ['followed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connect', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connect', type_='foreignkey')
    op.drop_constraint(None, 'connect', type_='foreignkey')
    op.create_foreign_key(op.f('connect_followed_id_fkey'), 'connect', 'posts', ['followed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('connect_follower_id_fkey'), 'connect', 'posts', ['follower_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
