"""renamed column name

Revision ID: 71ea2cc7bd82
Revises: cfbefe25d948
Create Date: 2025-10-21 15:20:28.239259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ea2cc7bd82'
down_revision: Union[str, Sequence[str], None] = 'cfbefe25d948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password', new_column_name='password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', new_column_name='hashed_password')
    # ### end Alembic commands ###
