"""followers and following columns added to users table

Revision ID: 7d1faa44d4d6
Revises: 2c174e8a19a1
Create Date: 2025-10-23 11:54:36.788731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1faa44d4d6'
down_revision: Union[str, Sequence[str], None] = '2c174e8a19a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('following', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('followers', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'following')
    op.drop_column('users', 'followers')
    # ### end Alembic commands ###
