"""renamed followers and following cols names

Revision ID: 87360d66e8c7
Revises: 7d1faa44d4d6
Create Date: 2025-10-23 12:01:17.676898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87360d66e8c7'
down_revision: Union[str, Sequence[str], None] = '7d1faa44d4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('followers_cnt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('following_cnt', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('users', 'followers')
    op.drop_column('users', 'following')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('following', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('followers', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('users', 'following_cnt')
    op.drop_column('users', 'followers_cnt')
    # ### end Alembic commands ###
