"""media col to posts

Revision ID: 8d516c168db3
Revises: 3605fed79bb3
Create Date: 2025-11-01 21:30:50.421055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d516c168db3'
down_revision: Union[str, Sequence[str], None] = '3605fed79bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_path', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('media_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'media_type')
    op.drop_column('posts', 'media_path')
    # ### end Alembic commands ###
