"""now bio can be empty

Revision ID: 8f77ecc4203e
Revises: e3f576b5f5aa
Create Date: 2025-10-31 17:12:19.468375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f77ecc4203e'
down_revision: Union[str, Sequence[str], None] = 'e3f576b5f5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'bio',
        existing_type=sa.String(),
        server_default="",
        existing_nullable=True,
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'bio',
        existing_type=sa.String(),
        server_default=None,  # Remove the server default
        existing_nullable=True,
        nullable=True,
    )
    # ### end Alembic commands ###
