"""now bio can be empty with value one empty space

Revision ID: ca01409f3fd7
Revises: 8f77ecc4203e
Create Date: 2025-10-31 17:20:40.882126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca01409f3fd7'
down_revision: Union[str, Sequence[str], None] = '8f77ecc4203e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'bio',
        existing_type=sa.String(),
        server_default=" ",
        existing_nullable=True,
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'bio',
        existing_type=sa.String(),
        server_default=None, 
        existing_nullable=True,
        nullable=True,
    )
    # ### end Alembic commands ###
