"""relationship b/w user to posts added

Revision ID: ca2d874b6ea6
Revises: cf9b16bf6604
Create Date: 2025-10-22 13:51:30.103862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2d874b6ea6'
down_revision: Union[str, Sequence[str], None] = 'cf9b16bf6604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
