"""added a new col to comments table

Revision ID: e3f576b5f5aa
Revises: ba96cfde0d92
Create Date: 2025-10-30 16:56:13.461996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f576b5f5aa'
down_revision: Union[str, Sequence[str], None] = 'ba96cfde0d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'comments',
        sa.Column('likes', sa.Integer(), server_default='0', nullable=False)
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments','likes')
    # ### end Alembic commands ###
