"""set bio to null

Revision ID: e67b6e05d01d
Revises: 65a3372aeccd
Create Date: 2025-10-31 17:55:37.960794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67b6e05d01d'
down_revision: Union[str, Sequence[str], None] = '65a3372aeccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'bio',
        existing_type=sa.String(),
        server_default=None,
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio', server_default=None, nullable=True)    # ### end Alembic commands ###
