"""set primary keys to false

Revision ID: fab4d9b9e6da
Revises: 6b6f456de93c
Create Date: 2025-10-23 19:33:44.304343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab4d9b9e6da'
down_revision: Union[str, Sequence[str], None] = '6b6f456de93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'post_id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_nullable=False,
                   primary_key=False)
    op.alter_column('comments', 'user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_nullable=False,
                   primary_key=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('comments', 'post_id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_nullable=False,
                   primary_key=True)
    op.alter_column('comments', 'user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_nullable=False,
                   primary_key=True)

    # ### end Alembic commands ###
